apiVersion: v1
kind: ServiceAccount
metadata:
  name: trace-ui-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trace-ui-cluster-role
rules:
- apiGroups: ["", "events.k8s.io"]
  resources: ["pods", "pods/log", "services", "namespaces", "nodes", "events", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trace-ui-cluster-binding
subjects:
- kind: ServiceAccount
  name: trace-ui-sa
  namespace: dev
roleRef:
  kind: ClusterRole
  name: trace-ui-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-log-viewer
  namespace: dev
  labels:
    app: web-log-viewer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web-log-viewer
  template:
    metadata:
      labels:
        app: web-log-viewer
    spec:
      serviceAccountName: trace-ui-sa
      containers:
      - name: trace-ui
        image: ims-trace-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          hostPort: 8888
          name: http
        volumeMounts:
        - name: letsencrypt-certs
          mountPath: /etc/letsencrypt
        - name: certbot-webroot
          mountPath: /var/www/certbot
        resources:
          requests:
            cpu: 20m
            memory: 30Mi
          limits:
            cpu: 300m
            memory: 250Mi
      volumes:
      - name: letsencrypt-certs
        hostPath:
          path: /etc/letsencrypt
          type: DirectoryOrCreate
      - name: certbot-webroot
        hostPath:
          path: /var/www/certbot
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: web-log-viewer
  namespace: dev
  labels:
    app: web-log-viewer
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: http
  selector:
    app: web-log-viewer
